TraversalCoreProject/Areas/Admin/Controllers/CommentController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace TraversalCoreProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CommentController : Controller
    {
        private readonly ICommentService _commentService;

        public CommentController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        public IActionResult Index()
        {
            var values = _commentService.TGetListCommentWithDestination();
            return View(values);
        }
        public IActionResult DeleteComment(int id)
        {
            var values = _commentService.TgetByID(id);
            _commentService.TDelete(values);
            return RedirectToAction("Index");
        }
    }
}

TraversalCoreProject/Areas/Member/Controllers/CommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TraversalCoreProject.Areas.Member.Controllers
{
    [Area("Member")]
    [AllowAnonymous]
    public class CommentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TraversalCoreProject/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace TraversalCoreProject.Controllers
{
    public class CommentController : Controller
    {
        CommentManager commentManager = new CommentManager(new EfCommentDal());
        private readonly UserManager<AppUser> _userManager;
        public CommentController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [HttpGet]
        public PartialViewResult AddComment()
        {
            // ViewBag.destID = id;
            //var value = await _userManager.FindByNameAsync(User.Identity.Name);
            //ViewBag.userID = 5;
            // ViewBag.a = "merhaba";
            return PartialView();
        }
        [HttpPost]
        public IActionResult AddComment(Comment p)
        {
            p.CommentDate = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            p.CommentState = true;
            commentManager.TAdd(p);
            return RedirectToAction("Index", "Destination");
        }
    }
}

TraversalCoreProject/Views/Comment/AddComment.cshtml
@if (User.Identity.IsAuthenticated)
{
    <div class="leave-comment-form mt-5" id="reply">
        <h4 class="side-title mb-2">Bir yorum bırakın</h4>
        <p class="mb-4">
            İşaretli alanları doldurmanız gerekmektedir.
        </p>
        <form method="post" asp-action="AddComment" asp-controller="Comment">
            <input type="hidden" name="DestinationID" value="@ViewBag.destID" />
            <input type="hidden" name="AppUserID" value="@ViewBag.userID" />
            <div class="form-group">
                <textarea name="CommentContent" class="form-control" placeholder="Yorumunuz*" required=""
                          spellcheck="false"></textarea>
            </div>
            <div class="submit text-right">
                <button class="btn btn-style btn-primary" type="submit" id="btnsave">Yorum Yap</button>
            </div>
        </form>
    </div>
}
else
{
    <h2>Yorum yapabilmek için üye olmanız gerekli.</h2>
}